"""
AgroGuardian AI — Government Schemes Service
CRUD operations for government agricultural schemes stored in MongoDB.
"""
from datetime import datetime
from utils.logger import get_logger
from utils.helpers import generate_id
from database import government_schemes_col

log = get_logger("service.schemes")
# ── Seed data (inserted on first run) ──
SEED_SCHEMES = [
    {
        "_id": generate_id(),
        "name": "PM-KISAN Samman Nidhi",
        "name_kn": "ಪಿಎಂ-ಕಿಸಾನ್ ಸಮ್ಮಾನ್ ನಿಧಿ",
        "name_hi": "पीएम-किसान सम्मान निधि",
        "description": "Direct income support of ₹6,000 per year to all landholding farmer families to help them purchase agricultural inputs.",
        "description_kn": "ಎಲ್ಲಾ ಭೂಹಿಡುವಳಿ ಹೊಂದಿರುವ ರೈತ ಕುಟುಂಬಗಳಿಗೆ ಕೃಷಿ ಪರಿಕರಗಳನ್ನು ಖರೀದಿಸಲು ಸಹಾಯ ಮಾಡಲು ವರ್ಷಕ್ಕೆ ₹6,000 ನೇರ ಆದಾಯದ ಬೆಂಬಲ.",
        "description_hi": "सभी भूमिधारक किसान परिवारों को कृषि इनपुट खरीदने में मदद करने के लिए प्रति वर्ष ₹6,000 की सीधी आय सहायता।",
        "benefit": "₹6,000 per year, distributed in three equal installments of ₹2,000 directly into the farmer's bank account.",
        "benefit_kn": "ವರ್ಷಕ್ಕೆ ₹6,000, ಮೂರು ಸಮಾನ ಕಂತುಗಳಲ್ಲಿ ತಲಾ ₹2,000 ರಂತೆ ನೇರವಾಗಿ ರೈತರ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಜಮೆ ಮಾಡಲಾಗುತ್ತದೆ.",
        "benefit_hi": "प्रति वर्ष ₹6,000, ₹2,000 की तीन समान किश्तों में सीधे किसान के बैंक खाते में वितरित।",
        "eligibility": "All landholding farmer families in India",
        "state": "All States",
        "category": "Income Support",
        "url": "https://pmkisan.gov.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "PM Fasal Bima Yojana",
        "name_kn": "ಪಿಎಂ ಫಸಲ್ ಬಿಮಾ ಯೋಜನೆ",
        "name_hi": "पीएम फसल बीमा योजना",
        "description": "Comprehensive crop insurance scheme providing financial support to farmers suffering crop loss due to natural calamities, pests, and diseases.",
        "description_kn": "ನೈಸರ್ಗಿಕ ವಿಕೋಪಗಳು, ಕೀಟಗಳು ಮತ್ತು ರೋಗಗಳಿಂದ ಬೆಳೆ ನಷ್ಟವನ್ನು ಅನುಭವಿಸುವ ರೈತರಿಗೆ ಆರ್ಥಿಕ ಬೆಂಬಲವನ್ನು ನೀಡುವ ಸಮಗ್ರ ಬೆಳೆ ವಿಮಾ ಯೋಜನೆ.",
        "description_hi": "प्राकृतिक आपदाओं, कीटों और बीमारियों के कारण फसल के नुकसान का सामना करने वाले किसानों को वित्तीय सहायता प्रदान करने वाली व्यापक फसल बीमा योजना।",
        "benefit": "Financial compensation and insurance coverage up to ₹2,00,000 per hectare for notified food and oilseed crops.",
        "benefit_kn": "ಅಧಿಸೂಚಿತ ಆಹಾರ ಮತ್ತು ಎಣ್ಣೆಕಾಳು ಬೆಳೆಗಳಿಗೆ ಪ್ರತಿ ಹೆಕ್ಟೇರ್‌ಗೆ ಗರಿಷ್ಠ ₹2,0,0,000 ವರೆಗೆ ಆರ್ಥಿಕ ಪರಿಹಾರ ಮತ್ತು ವಿಮಾ ರಕ್ಷಣೆ.",
        "benefit_hi": "अधिसूचित खाद्य और तिलहन फसलों के लिए प्रति हेक्टेयर ₹2,00,000 तक का वित्तीय मुआवजा और बीमा कवरेज।",
        "eligibility": "All farmers growing notified crops",
        "state": "All States",
        "category": "Insurance",
        "url": "https://pmfby.gov.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "Kisan Credit Card (KCC)",
        "name_kn": "ಕಿಸಾನ್ ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್ (KCC)",
        "name_hi": "किसान क्रेडिट कार्ड (KCC)",
        "description": "Provides farmers with timely and hassle-free access to short-term credit for cultivation, crop production, and maintenance needs.",
        "description_kn": "ರೈತರಿಗೆ ಕೃಷಿ, ಬೆಳೆ ಉತ್ಪಾದನೆ ಮತ್ತು ನಿರ್ವಹಣಾ ಅಗತ್ಯಗಳಿಗಾಗಿ ಸಮಯಕ್ಕೆ ಸರಿಯಾಗಿ ಮತ್ತು ಜಗಳ ಮುಕ್ತ ಅಲ್ಪಾವಧಿ ಸಾಲದ ಸೌಲಭ್ಯವನ್ನು ಒದಗಿಸುತ್ತದೆ.",
        "description_hi": "किसानों को खेती, फसल उत्पादन और रखरखाव की जरूरतों के लिए समय पर और परेशानी मुक्त अल्पकालिक ऋण प्रदान करता है।",
        "benefit": "Short-term credit limit up to ₹3,0,000 at a highly subsidized interest rate of 4% per annum with timely repayment.",
        "benefit_kn": "ಸಮಯಕ್ಕೆ ಸರಿಯಾಗಿ ಮರುಪಾವತಿ ಮಾಡಿದರೆ ವರ್ಷಕ್ಕೆ ಕೇವಲ 4% ರಷ್ಟು ರಿಯಾಯಿತಿ ಬಡ್ಡಿ ದರದಲ್ಲಿ ₹3,0,000 ವರೆಗೆ ಅಲ್ಪಾವಧಿ ಸಾಲ.",
        "benefit_hi": "समय पर पुनर्भुगतान करने पर प्रति वर्ष 4% की अत्यधिक रियायती ब्याज दर पर ₹3,0,000 तक की अल्पकालिक ऋण सीमा।",
        "eligibility": "Farmers, fishermen, and animal husbandry farmers",
        "state": "All States",
        "category": "Credit",
        "url": "https://www.pmkisan.gov.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "Raita Siri – Karnataka",
        "name_kn": "ರೈತ ಸಿರಿ – ಕರ್ನಾಟಕ",
        "name_hi": "रैत सिरी – कर्नाटक",
        "description": "Karnataka government scheme promoting the cultivation of minor millets by providing financial incentives directly to millet growers.",
        "description_kn": "ಕಿರು ಧಾನ್ಯಗಳ (ಸಿರಿಧಾನ್ಯ) ಬೆಳೆಗಾರರಿಗೆ ನೇರವಾಗಿ ಆರ್ಥಿಕ ಪ್ರೋತ್ಸಾಹವನ್ನು ನೀಡುವ ಮೂಲಕ ಸಿರಿಧಾನ್ಯಗಳ ಬೇಸಾಯವನ್ನು ಉತ್ತೇಜಿಸುವ ಕರ್ನಾಟಕ ರಾಜ್ಯ ಸರ್ಕಾರದ ಯೋಜನೆ.",
        "description_hi": "बाजरा उत्पादकों को सीधे वित्तीय प्रोत्साहन प्रदान करके छोटे बाजरा की खेती को बढ़ावा देने के लिए कर्नाटक राज्य सरकार की पहल।",
        "benefit": "Cash incentive of ₹10,000 per hectare directly credited to the bank accounts of registered millet farmers.",
        "benefit_kn": "ನೋಂದಾಯಿತ ಸಿರಿಧಾನ್ಯ ರೈತರ ಬ್ಯಾಂಕ್ ಖಾತೆಗಳಿಗೆ ನೇರವಾಗಿ ಪ್ರತಿ ಹೆಕ್ಟೇರ್‌ಗೆ ₹10,000 ನಗದು ಪ್ರೋತ್ಸಾಹ ಧನ ಜಮೆ.",
        "benefit_hi": "पंजीकृत बाजरा किसानों के बैंक खातों में सीधे ₹10,000 प्रति हेक्टेयर का नकद प्रोत्साहन हस्तांतरित।",
        "eligibility": "Registered millet farmers in Karnataka",
        "state": "Karnataka",
        "category": "State Scheme",
        "url": "https://raitamitra.karnataka.gov.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "PM Kisan Maan Dhan Yojana",
        "name_kn": "ಪಿಎಂ ಕಿಸಾನ್ ಮಾನ್ ಧನ್ ಯೋಜನೆ",
        "name_hi": "पीएम किसान मान धन योजना",
        "description": "Voluntary and contributory pension scheme for small and marginal farmers to provide social security and financial stability in old age.",
        "description_kn": "ಸಣ್ಣ ಮತ್ತು ಅತಿ ಸಣ್ಣ ರೈತರಿಗೆ ವೃದ್ಧಾಪ್ಯದಲ್ಲಿ ಸಾಮಾಜಿಕ ಭದ್ರತೆ ಮತ್ತು ಆರ್ಥಿಕ ಸ್ಥಿರತೆಯನ್ನು ಒದಗಿಸಲು ಸ್ವಯಂಪ್ರೇರಿತ ಮತ್ತು ಕೊಡುಗೆ ಆಧಾರಿತ ಪಿಂಚಣಿ ಯೋಜನೆ.",
        "description_hi": "वृद्धावस्था में सामाजिक सुरक्षा और वित्तीय स्थिरता प्रदान करने के लिए छोटे और सीमांत किसानों के लिए स्वैच्छिक और अंशदायी पेंशन योजना।",
        "benefit": "Guaranteed monthly pension of ₹3,000 after attaining the age of 60 years, with minimal monthly contributions.",
        "benefit_kn": "ಕನಿಷ್ಠ ಮಾಸಿಕ ಕೊಡುಗೆಯೊಂದಿಗೆ, 60 ವರ್ಷ ವಯಸ್ಸನ್ನು ತಲುಪಿದ ನಂತರ ಮಾಸಿಕ ₹3,000 ಖಾತರಿ ಪಿಂಚಣಿ.",
        "benefit_hi": "60 वर्ष की आयु प्राप्त करने के बाद न्यूनतम मासिक योगदान के साथ ₹3,000 की गारंटीकृत मासिक पेंशन।",
        "eligibility": "Small and marginal farmers aged 18 to 40 years",
        "state": "All States",
        "category": "Pension",
        "url": "https://maandhan.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "PMKSY – Per Drop More Crop",
        "name_kn": "ಪಿಎಂಕೆಎಸ್‌ವೈ – ಪರ್ ಡ್ರಾಪ್ ಮೋರ್ ಕ್ರಾಪ್",
        "name_hi": "पीएमकेएसवाई – पर ड्रॉप मोर क्रॉप",
        "description": "Focuses on improving water use efficiency at the farm level through modern micro-irrigation technologies like drip and sprinkler systems.",
        "description_kn": "ಹನಿ ಮತ್ತು ಸಿಂಪಡಣೆ (ಸ್ಪ್ರಿಂಕ್ಲರ್) ವ್ಯವಸ್ಥೆಗಳಂತಹ ಆಧುನಿಕ ಸೂಕ್ಷ್ಮ ನೀರಾವರಿ ತಂತ್ರಜ್ಞಾನಗಳ ಮೂಲಕ ಜಮೀನಿನಲ್ಲಿ ನೀರಿನ ಬಳಕೆಯ ದಕ್ಷತೆಯನ್ನು ಸುಧಾರಿಸುವ ಯೋಜನೆ.",
        "description_hi": "टपकन (ड्रिप) और छिड़काव (स्प्रिंकलर) जैसी आधुनिक सूक्ष्म सिंचाई तकनीकों के माध्यम से कृषि स्तर पर जल उपयोग दक्षता में सुधार पर ध्यान केंद्रित करता है।",
        "benefit": "Subsidy of up to 90% of the total installation cost of drip and sprinkler irrigation systems for small and marginal farmers.",
        "benefit_kn": "ಸಣ್ಣ ಮತ್ತು ಅತಿ ಸಣ್ಣ ರೈತರಿಗೆ ಹನಿ ಮತ್ತು ತುಂತುರು ನೀರಾವರಿ ವ್ಯವಸ್ಥೆಗಳ ಒಟ್ಟು ವೆಚ್ಚದ ಮೇಲೆ ಶೇಕಡಾ 90 ರವರೆಗೆ ಸಬ್ಸಿಡಿ.",
        "benefit_hi": "छोटे और सीमांत किसानों के लिए ड्रिप और स्प्रिंकलर सिंचाई प्रणालियों की कुल स्थापना लागत पर 90% तक की सब्सिडी।",
        "eligibility": "All landholding farmers in India",
        "state": "All States",
        "category": "Irrigation",
        "url": "https://pmksy.gov.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "Paramparagat Krishi Vikas Yojana (PKVY)",
        "name_kn": "ಪರಂಪರಾಗತ್ ಕೃಷಿ ವಿಕಾಸ್ ಯೋಜನೆ (PKVY)",
        "name_hi": "परंपरागत कृषि विकास योजना (PKVY)",
        "description": "Promotes commercial organic farming through cluster models, participatory guarantee system certification, and organic input subsidies.",
        "description_kn": "ಕ್ಲಸ್ಟರ್ ಮಾದರಿಗಳು, ಸಾವಯವ ಪ್ರಮಾಣೀಕರಣ ಮತ್ತು ಸಾವಯವ ಪರಿಕರಗಳ ಸಬ್ಸಿಡಿಗಳ ಮೂಲಕ ವಾಣಿಜ್ಯ ಸಾವಯವ ಕೃಷಿಯನ್ನು ಉತ್ತೇಜಿಸುವ ಯೋಜನೆ.",
        "description_hi": "क्लस्टर मॉडल, सहभागी गारंटी प्रणाली प्रमाणन और जैविक इनपुट सब्सिडी के माध्यम से व्यावसायिक जैविक खेती को बढ़ावा देता है।",
        "benefit": "Financial assistance of ₹50,000 per hectare over 3 years, covering organic seed purchase, harvesting, and marketing.",
        "benefit_kn": "ಸಾವಯವ ಬೀಜ ಖರೀದಿ, ಕೊಯ್ಲು ಮತ್ತು ಮಾರುಕಟ್ಟೆ ವೆಚ್ಚಗಳಿಗಾಗಿ 3 ವರ್ಷಗಳಲ್ಲಿ ಪ್ರತಿ ಹೆಕ್ಟೇರ್‌ಗೆ ₹50,000 ಆರ್ಥಿಕ ಸಹಾಯ.",
        "benefit_hi": "जैविक बीज खरीद, कटाई और विपणन को कवर करने के लिए 3 वर्षों में ₹50,000 प्रति हेक्टेयर की वित्तीय सहायता।",
        "eligibility": "Farmers forming organic farming clusters of 50 or more",
        "state": "All States",
        "category": "Organic Farming",
        "url": "https://pgsindia-ncof.gov.in/pkvy/index.html",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "Sub-Mission on Agricultural Mechanization (SMAM)",
        "name_kn": "ಸಬ್-ಮಿಷನ್ ಆನ್ ಅಗ್ರಿಕಲ್ಚರಲ್ ಮೆಕನೈಸೇಶನ್ (SMAM)",
        "name_hi": "सब-मिशन ऑन एग्रीकल्चरल मैकेनाइजेशन (SMAM)",
        "description": "Promotes farm mechanization by providing subsidies for purchasing tractors, power tillers, rotavators, and high-tech custom hiring equipment.",
        "description_kn": "ಟ್ರಾಕ್ಟರ್‌ಗಳು, ಪವರ್ ಟಿಲ್ಲರ್‌ಗಳು, ರೋಟಾವೇಟರ್‌ಗಳು ಮತ್ತು ಸುಧಾರಿತ ಯಂತ್ರೋಪಕರಣಗಳ ಖರೀದಿಗೆ ಸಬ್ಸಿಡಿ ನೀಡುವ ಮೂಲಕ ಕೃಷಿ ಯಾಂತ್ರೀಕರಣವನ್ನು ಉತ್ತೇಜಿಸುತ್ತದೆ.",
        "description_hi": "ट्रैक्टर, पावर टिलर, रोटावेटर और हाई-टेक कस्टम हायरिंग उपकरणों की खरीद के लिए सब्सिडी प्रदान करके कृषि मशीनीकरण को बढ़ावा देता है।",
        "benefit": "Financial subsidy of 40% to 50% on the purchase price of agricultural machinery, with up to 80% for custom hiring centers.",
        "benefit_kn": "ಕೃಷಿ ಯಂತ್ರೋಪಕರಣಗಳ ಖರೀದಿ ಬೆಲೆಯ ಮೇಲೆ ಶೇಕಡಾ 40 ರಿಂದ 50 ರಷ್ಟು ಸಬ್ಸಿಡಿ, ಮತ್ತು ಕಸ್ಟಮ್ ಹೈರಿಂಗ್ ಕೇಂದ್ರಗಳಿಗೆ ಶೇಕಡಾ 80 ರವರೆಗೆ ಸಬ್ಸಿಡಿ.",
        "benefit_hi": "कृषि मशीनरी की खरीद कीमत पर 40% से 50% की वित्तीय सब्सिडी, कस्टम हायरिंग केंद्रों के लिए 80% तक की सब्सिडी।",
        "eligibility": "Small, marginal, and women farmers",
        "state": "All States",
        "category": "Machinery",
        "url": "https://agrimachinery.nic.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "PM Matsya Sampada Yojana (PMMSY)",
        "name_kn": "ಪಿಎಂ ಮತ್ಸ್ಯ ಸಂಪದ ಯೋಜನೆ (PMMSY)",
        "name_hi": "पीएम मत्स्य संपदा योजना (PMMSY)",
        "description": "Aims to ecologically and economically develop the fisheries sector through modernization, fisheries infrastructure creation, and value chain support.",
        "description_kn": "ಆಧುನೀಕರಣ, ಮೀನುಗಾರಿಕೆ ಮೂಲಸೌಕರ್ಯಗಳ ರಚನೆ ಮತ್ತು ಮೌಲ್ಯ ಸರಪಳಿ ಬೆಂಬಲದ ಮೂಲಕ ಮೀನುಗಾರಿಕೆ ವಲಯವನ್ನು ಪರಿಸರ ಮತ್ತು ಆರ್ಥಿಕವಾಗಿ ಅಭಿವೃದ್ಧಿಪಡಿಸುವ ಗುರಿಯನ್ನು ಹೊಂದಿದೆ.",
        "description_hi": "आधुनिकीकरण, मत्स्य पालन बुनियादी ढांचे के निर्माण और मूल्य श्रृंखला सहायता के माध्यम से मत्स्य पालन क्षेत्र को पारिस्थितिक और आर्थिक रूप से विकसित करना है।",
        "benefit": "Financial subsidy of 40% for general category and 60% for SC/ST/women for setting up aquaculture ponds and cold storage.",
        "benefit_kn": "ಮೀನು ಸಾಕಣೆ ಕೊಳಗಳು ಮತ್ತು ಶೀತಲ ಸಂಗ್ರಹಣಾ ಘಟಕಗಳನ್ನು ಸ್ಥಾಪಿಸಲು ಸಾಮಾನ್ಯ ವರ್ಗಕ್ಕೆ 40% ಮತ್ತು ಎಸ್‌ಸಿ/ಎಸ್‌ಟಿ/ಮಹಿಳೆಯರಿಗೆ 60% ಆರ್ಥಿಕ ಸಬ್ಸಿಡಿ.",
        "benefit_hi": "एक्वाकल्चर तालाबों और कोल्ड स्टोरेज की स्थापना के लिए सामान्य श्रेणी के लिए 40% और एससी/एसटी/महिलाओं के लिए 60% वित्तीय सब्सिडी।",
        "eligibility": "Fish farmers, fish workers, and cooperatives",
        "state": "All States",
        "category": "Aquaculture",
        "url": "https://pmmsy.dof.gov.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "Krishi Karunya Scheme (Karnataka)",
        "name_kn": "ಕೃಷಿ ಕಾರುಣ್ಯ ಯೋಜನೆ (ಕರ್ನಾಟಕ)",
        "name_hi": "कृषि कारुण्या योजना (कर्नाटक)",
        "description": "Provides accidental death and permanent disability insurance coverage to registered farmers in the state of Karnataka.",
        "description_kn": "ಕರ್ನಾಟಕ ರಾಜ್ಯದ ನೋಂದಾಯಿತ ರೈತರಿಗೆ ಆಕಸ್ಮಿಕ ಮರಣ ಮತ್ತು ಶಾಶ್ವತ ಅಂಗವಿಕಲತೆಗೆ ವಿಮಾ ರಕ್ಷಣೆ ಒದಗಿಸುವ ರಾಜ್ಯ ಸರ್ಕಾರದ ಯೋಜನೆ.",
        "description_hi": "कर्नाटक राज्य में पंजीकृत किसानों को आकस्मिक मृत्यु और स्थायी विकलांगता बीमा कवरेज प्रदान करता है।",
        "benefit": "Ex-gratia financial assistance of ₹5,00,000 to the family of the farmer in case of accidental death during agricultural work.",
        "benefit_kn": "ಕೃಷಿ ಕೆಲಸದ ಸಮಯದಲ್ಲಿ ಆಕಸ್ಮಿಕ ಮರಣ ಹೊಂದಿದಲ್ಲಿ ರೈತರ ಕುಟುಂಬಕ್ಕೆ ₹5,00,000 ವರೆಗೆ ಪರಿಹಾರ ಧನ.",
        "benefit_hi": "कृषि कार्य के दौरान आकस्मिक मृत्यु के मामले में किसान के परिवार को ₹5,00,000 की अनुग्रह वित्तीय सहायता।",
        "eligibility": "Registered farmers in Karnataka",
        "state": "Karnataka",
        "category": "State Scheme",
        "url": "https://raitamitra.karnataka.gov.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "Har Khet Ko Pani (PMKSY-HKKP)",
        "name_kn": "ಹರ್ ಖೇತ್ ಕೋ ಪಾನಿ (PMKSY-HKKP)",
        "name_hi": "हर खेत को पानी (PMKSY-HKKP)",
        "description": "Focuses on creating new water sources, expanding cultivable command areas, and distributing water-saving surface irrigation systems.",
        "description_kn": "ಹೊಸ ನೀರಿನ ಮೂಲಗಳನ್ನು ಸೃಜಿಸುವುದು, ಸಾಗುವಳಿ ಯೋಗ್ಯ ಜಮೀನಿನ ವಿಸ್ತರಣೆ ಮತ್ತು ಉಳಿತಾಯದ ಮೇಲ್ಮೈ ನೀರಾವರಿ ವ್ಯವಸ್ಥೆಗಳ ವಿತರಣೆಯ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸುತ್ತದೆ.",
        "description_hi": "नए जल स्रोतों के निर्माण, कृषि योग्य कमान क्षेत्रों के विस्तार और पानी बचाने वाली सतही सिंचाई प्रणालियों के वितरण पर ध्यान केंद्रित करता है।",
        "benefit": "Subsidizes up to 70% of the cost for community water harvesting structures, borewell rejuvenation, and field channels.",
        "benefit_kn": "ಸಾಮುದಾಯಿಕ ನೀರು ಕೊಯ್ಲು ರಚನೆಗಳು, ಕೊಳವೆಬಾವಿ ಪುನಶ್ಚೇತನ ಮತ್ತು ಕಾಲುವೆಗಳ ನಿರ್ಮಾಣದ ವೆಚ್ಚದ ಮೇಲೆ ಶೇಕಡಾ 70 ರವರೆಗೆ ಸಬ್ಸಿಡಿ.",
        "benefit_hi": "सामुदायिक जल संचयन संरचनाओं, नलकूप पुनरुद्धार और मैदानी नहरों के लिए लागत का 70% तक सब्सिडी प्रदान करता है।",
        "eligibility": "All landholding farmers and community groups",
        "state": "All States",
        "category": "Irrigation",
        "url": "https://pmksy.gov.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "National Horticulture Mission (NHM)",
        "name_kn": "ನ್ಯಾಷನಲ್ ಹಾರ್ಟಿಕಲ್ಚರ್ ಮಿಷನ್ (NHM)",
        "name_hi": "नेशनल हॉर्टिकल्चर मिशन (NHM)",
        "description": "Promotes holistic growth of the horticulture sector, including fruits, vegetables, root and tuber crops, mushrooms, spices, and flowers.",
        "description_kn": "ಹಣ್ಣುಗಳು, ತರಕಾರಿಗಳು, ಗೆಡ್ಡೆ ಗೆಣಸು ಬೆಳೆಗಳು, ಅಣಬೆಗಳು, ಸಾಂಬಾರ ಪದಾರ್ಥಗಳು ಮತ್ತು ಹೂವುಗಳು ಸೇರಿದಂತೆ ತೋಟಗಾರಿಕಾ ವಲಯದ ಸಮಗ್ರ ಬೆಳವಣಿಗೆಯನ್ನು ಉತ್ತೇಜಿಸುತ್ತದೆ.",
        "description_hi": "बागवानी क्षेत्र के समग्र विकास को बढ़ावा देता है, जिसमें फल, सब्जियां, कंद फसलें, मशरूम, मसाले और फूल शामिल हैं।",
        "benefit": "Up to 50% financial subsidy for establishing new orchards, nursery setups, protected cultivation (polyhouses), and cold storage.",
        "benefit_kn": "ಹೊಸ ತೋಟಗಳು, ನರ್ಸರಿಗಳು, ಸಂರಕ್ಷಿತ ಬೇಸಾಯ (ಪಾಲಿಹೌಸ್) ಮತ್ತು ಶೀತಲ ಸಂಗ್ರಹಣಾ ಘಟಕಗಳ ಸ್ಥಾಪನೆಗೆ ಶೇಕಡಾ 50 ರವರೆಗೆ ಆರ್ಥಿಕ ಸಬ್ಸಿಡಿ.",
        "benefit_hi": "नए बागों की स्थापना, नर्सरी परीक्षा, संरक्षित खेती (पॉलीहाउस) और कोल्ड स्टोरेज के लिए 50% तक वित्तीय सब्सिडी।",
        "eligibility": "Farmers growing horticultural and organic crops",
        "state": "All States",
        "category": "Horticulture",
        "url": "https://midh.gov.in/nhm.html",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "Agri-Clinics & Agri-Business Centres (ACABC)",
        "name_kn": "ಅಗ್ರಿ-ಕ್ಲಿನಿಕ್ಸ್ ಮತ್ತು ಅಗ್ರಿ-ಬಿಸಿನೆಸ್ ಸೆಂಟರ್ಸ್ (ACABC)",
        "name_hi": "एग्री-क्लिनिक्स एंड एग्री-बिजनेस सेंटर्स (ACABC)",
        "description": "Supports agricultural graduates and entrepreneurs to set up custom service centers and agri-ventures to advise farmers.",
        "description_kn": "ಕೃಷಿ ಪದವೀಧರರು ಮತ್ತು ಉದ್ಯಮಿಗಳು ರೈತರಿಗೆ ಸಲಹೆ ನೀಡಲು ಕಸ್ಟಮ್ ಸೇವಾ ಕೇಂದ್ರಗಳು ಮತ್ತು ಕೃಷಿ ಉದ್ಯಮಗಳನ್ನು ಸ್ಥಾಪಿಸಲು ಬೆಂಬಲ ನೀಡುತ್ತದೆ.",
        "description_hi": "कृषि स्नातकों और उद्यमियों को किसानों को सलाह देने के लिए कस्टम सेवा केंद्र और कृषि-उद्यम स्थापित करने में सहायता करता है।",
        "benefit": "Provides credit-linked capital subsidy of 36% (general) to 44% (SC/ST/women) on bank loans up to ₹20,00,000.",
        "benefit_kn": "₹20,00,000 ವರೆಗಿನ ಬ್ಯಾಂಕ್ ಸಾಲಗಳ ಮೇಲೆ ಶೇಕಡಾ 36 (ಸಾಮಾನ್ಯ) ರಿಂದ ಶೇಕಡಾ 44 (ಎಸ್‌ಸಿ/ಎಸ್‌ಟಿ/ಮಹಿಳಾ) ರವರೆಗೆ ಬಂಡವಾಳ ಸಬ್ಸಿಡಿ.",
        "benefit_hi": "₹20,00,000 तक के बैंक ऋण पर 36% (सामान्य) से 44% (एससी/एसटी/महिला) की क्रेडिट-लिंक्ड पूंजी सब्सिडी प्रदान करता है।",
        "eligibility": "Agriculture graduates, diploma holders, and rural entrepreneurs",
        "state": "All States",
        "category": "Credit",
        "url": "https://www.agriclinics.net",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "Weather-Based Crop Insurance Scheme (WBCIS)",
        "name_kn": "ವೆದರ್-ಬೇಸ್ಡ್ ಕ್ರಾಪ್ ಇನ್ಶೂರೆನ್ಸ್ ಸ್ಕೀಮ್ (WBCIS)",
        "name_hi": "वेदर-बेस्ड क्रॉप इंश्योरेंस स्कीम (WBCIS)",
        "description": "Provides insurance payouts to farmers based on adverse weather indices like excess rainfall, heatwaves, or high humidity triggering diseases.",
        "description_kn": "ಅತಿಯಾದ ಮಳೆ, ಬಿಸಿಲಿನ ಬೇಗೆ ಅಥವಾ ರೋಗಗಳಿಗೆ ಕಾರಣವಾಗುವ ಹೆಚ್ಚಿನ ಆರ್ದ್ರತೆಯಂತಹ ಪ್ರತಿಕೂಲ ಹವಾಮಾನ ಸೂಚ್ಯಂಕಗಳ ಆಧಾರದ ಮೇಲೆ ರೈತರಿಗೆ ವಿಮಾ ಪರಿಹಾರ ಒದಗಿಸುತ್ತದೆ.",
        "description_hi": "अत्यधिक वर्षा, लू या बीमारियों को ट्रिगर करने वाली उच्च आर्द्रता जैसे प्रतिकूल मौसम सूचकांकों के आधार पर किसानों को बीमा भुगतान प्रदान करता है।",
        "benefit": "Compensates farmers for yield losses calculated using weather deviation data from local automated weather stations.",
        "benefit_kn": "ಸ್ಥಳೀಯ ಸ್ವಯಂಚಾಲಿತ ಹವಾಮಾನ ಕೇಂದ್ರಗಳ ಹವಾಮಾನ ವಿಚಲನ ದತ್ತಾಂಶವನ್ನು ಬಳಸಿಕೊಂಡು ಲೆಕ್ಕಹಾಕಿದ ಇಳುವರಿ ನಷ್ಟಕ್ಕೆ ರೈತರಿಗೆ ಪರಿಹಾರ ನೀಡುತ್ತದೆ.",
        "benefit_hi": "स्थानीय स्वचालित मौसम स्टेशनों से मौसम विचलन डेटा का उपयोग करके गणना की गई उपज हानि के लिए किसानों को मुआवजा देता है।",
        "eligibility": "All farmers growing notified crops",
        "state": "All States",
        "category": "Insurance",
        "url": "https://pmfby.gov.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "Integrated Pest Management (IPM) Promotion Scheme",
        "name_kn": "ಇಂಟಿಗ್ರೇಟೆಡ್ ಪೆಸ್ಟ್ ಮ್ಯಾನೇಜ್ಮೆಂಟ್ (IPM) ಪ್ರಮೋಷನ್ ಸ್ಕೀಮ್",
        "name_hi": "इंटीग्रेटेड पेस्ट मैनेजमेंट (IPM) प्रमोशन स्कीम",
        "description": "Promotes eco-friendly pest and disease control through biological agents, pheromone traps, and bio-pesticides to minimize chemical use.",
        "description_kn": "ರಾಸಾಯನಿಕಗಳ ಬಳಕೆಯನ್ನು ಕಡಿಮೆ ಮಾಡಲು ಜೈವಿಕ ಏಜೆಂಟ್‌ಗಳು, ಫೆರೋಮೋನ್ ಬಲೆಗಳು ಮತ್ತು ಜೈವಿಕ ಕೀಟನಾಶಕಗಳ ಮೂಲಕ ಪರಿಸರಸ್ನೇಹಿ ಕೀಟ ಮತ್ತು ರೋಗ ನಿಯಂತ್ರಣವನ್ನು ಉತ್ತೇಜಿಸುತ್ತದೆ.",
        "description_hi": "रासायनिक उपयोग को कम करने के लिए जैविक एजेंटों, फेरोमोन ट्रैप और जैव-कीटनाशकों के माध्यम से पर्यावरण के अनुकूल कीट और रोग नियंत्रण को बढ़ावा देता है।",
        "benefit": "Provides 50% financial subsidy on biological inputs, neem-based sprays, pheromone traps, and biological control agents.",
        "benefit_kn": "ಜೈವಿಕ ಪರಿಕರಗಳು, ಬೇವಿನ ಆಧಾರಿತ ಸಿಂಪಡಣೆಗಳು, ಫೆರೋಮೋನ್ ಬಲೆಗಳು ಮತ್ತು ಜೈವಿಕ ನಿಯಂತ್ರಣ ಏಜೆಂಟ್‌ಗಳ ಮೇಲೆ ಶೇಕಡಾ 50 ರಷ್ಟು ಆರ್ಥಿಕ ಸಬ್ಸಿಡಿ.",
        "benefit_hi": "जैविक इनपुट, नीम आधारित स्प्रे, फेरोमोन ट्रैप और जैविक नियंत्रण एजेंटों पर 50% वित्तीय सब्सिडी प्रदान करता है।",
        "eligibility": "Small, marginal, and cooperative farmers",
        "state": "All States",
        "category": "Crop Protection",
        "url": "https://dacfw.nic.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "National Horticulture Board (NHB) Subsidy",
        "name_kn": "ನ್ಯಾಷನಲ್ ಹಾರ್ಟಿಕಲ್ಚರ್ ಬೋರ್ಡ್ (NHB) ಸಬ್ಸಿಡಿ",
        "name_hi": "नेशनल हॉर्टिकल्चर बोर्ड (NHB) सब्सिडी",
        "description": "Aims to develop commercial horticulture, improve post-harvest management, and establish cold chain infrastructures across India.",
        "description_kn": "ವಾಣಿಜ್ಯ ತೋಟಗಾರಿಕೆಯನ್ನು ಅಭಿವೃದ್ಧಿಪಡಿಸುವುದು, ಕೊಯ್ಲೋತ್ತರ ನಿರ್ವಹಣೆಯನ್ನು ಸುಧಾರಿಸುವುದು ಮತ್ತು ಭಾರತದಾದ್ಯಂತ ಶೀತಲ ಸರಪಳಿ ಮೂಲಸೌಕರ್ಯಗಳನ್ನು ಸ್ಥಾಪಿಸುವ ಗುರಿಯನ್ನು ಹೊಂದಿದೆ.",
        "description_hi": "व्यावसायिक बागवानी विकसित करना, कटाई के बाद के प्रबंधन में सुधार करना और पूरे भारत में कोल्ड चेन बुनियादी ढांचे की स्थापना करना है।",
        "benefit": "Provides capital investment subsidy of 40% to 50% for commercial horticulture projects up to ₹30,00,000.",
        "benefit_kn": "₹30,00,000 ವರೆಗಿನ ವಾಣಿಜ್ಯ ತೋಟಗಾರಿಕಾ ಯೋಜನೆಗಳಿಗೆ ಶೇಕಡಾ 40 ರಿಂದ 50 ರವರೆಗೆ ಬಂಡವಾಳ ಹೂಡಿಕೆ ಸಬ್ಸಿಡಿ.",
        "benefit_hi": "₹30,00,000 तक की व्यावसायिक बागवानी परियोजनाओं के लिए 40% से 50% की पूंजी निवेश सब्सिडी प्रदान करता है।",
        "eligibility": "Individual farmers, self-help groups, and cooperatives",
        "state": "All States",
        "category": "Horticulture",
        "url": "https://nhb.gov.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "Bayer CropScience Food Chain Partnership",
        "name_kn": "ಬಾಯರ್ ಕ್ರಾಪ್ ಸೈನ್ಸ್ ಫುಡ್ ಚೈನ್ ಪಾರ್ಟ್‌ನರ್‌ಶಿಪ್",
        "name_hi": "बायर क्रॉपसाइंस फूड चैन साझेदारी",
        "description": "A private initiative to train smallholder farmers in modern agronomy, disease forecasting, and global food safety compliance.",
        "description_kn": "ಸಣ್ಣ ರೈತರಿಗೆ ಆಧುನಿಕ ಕೃಷಿ ವಿಜ್ಞಾನ, ರೋಗ ಮುನ್ಸೂಚನೆ ಮತ್ತು ಜಾಗತಿಕ ಆಹಾರ ಸುರಕ್ಷತಾ ಅನುಸರಣೆಯಲ್ಲಿ ತರಬೇತಿ ನೀಡುವ ಖಾಸಗಿ ಉಪಕ್ರಮ.",
        "description_hi": "छोटे किसानों को आधुनिक कृषि विज्ञान, रोग पूर्वानुमान और वैश्विक खाद्य सुरक्षा अनुपालन में प्रशिक्षित करने की एक निजी पहल।",
        "benefit": "Provides free access to digital disease monitoring tools, expert field agronomy advice, and certified pest-resistant seeds.",
        "benefit_kn": "ಡಿಜಿಟಲ್ ರೋಗ ಮೇಲ್ವಿಚಾರಣೆ ಪರಿಕರಗಳು, ತಜ್ಞರ ಕ್ಷೇತ್ರ ಕೃಷಿ ಸಲಹೆ ಮತ್ತು ಪ್ರಮಾಣೀಕೃತ ಕೀಟ-ನಿರೋಧಕ ಬೀಜಗಳಿಗೆ ಉಚಿತ ಪ್ರವೇಶ.",
        "benefit_hi": "डिजिटल रोग निगरानी उपकरण, विशेषज्ञ कृषि सलाह और प्रमाणित कीट-प्रतिरोधी बीजों तक मुफ्त पहुंच प्रदान करता है।",
        "eligibility": "Farmers registered in participating crop clusters",
        "state": "All States",
        "category": "Private Initiative",
        "url": "https://www.bayer.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "Soil Health Card Scheme",
        "name_kn": "ಸಾಯಿಲ್ ಹೆಲ್ತ್ ಕಾರ್ಡ್ ಸ್ಕೀಮ್",
        "name_hi": "सॉइल हेल्थ कार्ड स्कीम",
        "description": "Assesses soil nutrient status and provides farmers with customized fertilizer and soil conditioner dosage recommendations.",
        "description_kn": "ಮಣ್ಣಿನ ಪೋಷಕಾಂಶಗಳ ಸ್ಥಿತಿಯನ್ನು ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತದೆ ಮತ್ತು ರೈತರಿಗೆ ಕಸ್ಟಮೈಸ್ ಮಾಡಿದ ರಸಗೊಬ್ಬರ ಮತ್ತು ಮಣ್ಣಿನ ಕಂಡಿಷನರ್ ಡೋಸೇಜ್ ಶಿಫಾರಸುಗಳನ್ನು ಒದಗಿಸುತ್ತದೆ.",
        "description_hi": "मिट्टी के पोषक तत्वों की स्थिति का आकलन करता है और किसानों को अनुकूलित उर्वरक और मिट्टी कंडीशनर खुराक की सिफारिशें प्रदान करता है।",
        "benefit": "Provides free soil testing once every 2 years and a printed health card detailing corrective nutrient measures.",
        "benefit_kn": "ಪ್ರತಿ 2 ವರ್ಷಗಳಿಗೊಮ್ಮೆ ಉಚಿತ ಮಣ್ಣಿನ ಪರೀಕ್ಷೆ ಮತ್ತು ಸರಿಪಡಿಸುವ ಪೋಷಕಾಂಶ ಕ್ರಮಗಳನ್ನು ವಿವರಿಸುವ ಮುದ್ರಿತ ಆರೋಗ್ಯ ಕಾರ್ಡ್ ಅನ್ನು ಒದಗಿಸುತ್ತದೆ.",
        "benefit_hi": "हर 2 साल में एक बार मुफ्त मिट्टी परीक्षण और सुधारात्मक पोषक तत्वों के उपायों का विवरण देने वाला एक मुद्रित स्वास्थ्य कार्ड प्रदान करता है।",
        "eligibility": "All landholding farmers in India",
        "state": "All States",
        "category": "Soil Health",
        "url": "https://soilhealth.dac.gov.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "NABARD Plantation and Horticulture Loan",
        "name_kn": "ನಬಾರ್ಡ್ ಪ್ಲಾಂಟೇಶನ್ ಮತ್ತು ಹಾರ್ಟಿಕಲ್ಚರ್ ಲೋನ್",
        "name_hi": "नाबार्ड प्लांटेशन एंड हॉर्टिकल्चर लोन",
        "description": "Refinances commercial banks to offer long-term loans for establishing orchards, replacing old plantations, or recovering from crop disease epidemics.",
        "description_kn": "ವಾಣಿಜ್ಯ ಬ್ಯಾಂಕುಗಳಿಗೆ ಮರುಕಡಿತ ಸೌಲಭ್ಯ ನೀಡುವ ಮೂಲಕ ರೈತರು ತೋಟಗಳನ್ನು ಸ್ಥಾಪಿಸಲು, ಹಳೆಯ ತೋಟಗಳನ್ನು ಬದಲಿಸಲು ಅಥವಾ ಸಾಂಕ್ರಾಮಿಕ ರೋಗಗಳಿಂದ ಚೇತರಿಸಿಕೊಳ್ಳಲು ದೀರ್ಘಾವಧಿ ಸಾಲ ನೀಡುತ್ತದೆ.",
        "description_hi": "व्यावसायिक बैंकों को पुनर्वित्त प्रदान करता है ताकि वे बागों की स्थापना, पुराने बागों को बदलने या फसल रोग महामारी से उबरने के लिए दीर्घकालिक ऋण प्रदान कर सकें।",
        "benefit": "Long-term credit covering up to 90% of the project cost with a flexible repayment period of 5 to 15 years.",
        "benefit_kn": "ಯೋಜನಾ ವೆಚ್ಚದ ಶೇಕಡಾ 90 ರಷ್ಟನ್ನು ಒಳಗೊಳ್ಳುವ ದೀರ್ಘಾವಧಿ ಸಾಲ ಮತ್ತು 5 ರಿಂದ 15 ವರ್ಷಗಳ ಹೊಂದಿಕೊಳ್ಳುವ ಸಾಲ ಮರುಪಾವತಿ ಅವಧಿ.",
        "benefit_hi": "परियोजना लागत के 90% तक को कवर करने वाला दीर्घकालिक ऋण, जिसमें 5 से 15 वर्ष की लचीली पुनर्भुगतान अवधि होती है।",
        "eligibility": "Individual orchard owners and farmers",
        "state": "All States",
        "category": "Credit",
        "url": "https://www.nabard.org",
        "active": True,
    },
    # ── MAHARASHTRA ──
    {
        "_id": generate_id(),
        "name": "MahaDBT Farmer Scheme",
        "name_kn": "ಮಹಾಡಿಬಿಟಿ ರೈತ ಯೋಜನೆ",
        "name_hi": "महाडीबीटी किसान योजना",
        "description": "Direct Benefit Transfer scheme by the Maharashtra government providing subsidies for farm mechanization, irrigation, and seeds.",
        "description_kn": "ಕೃಷಿ ಯಾಂತ್ರೀಕರಣ, ನೀರಾವರಿ ಮತ್ತು ಬಿತ್ತನೆ ಬೀಜಗಳಿಗೆ ಸಬ್ಸಿಡಿ ನೀಡುವ ಮಹಾರಾಷ್ಟ್ರ ಸರ್ಕಾರದ ನೇರ ಸೌಲಭ್ಯ ವರ್ಗಾವಣೆ ಯೋಜನೆ.",
        "description_hi": "कृषि मशीनीकरण, सिंचाई और बीजों के लिए सब्सिडी प्रदान करने वाली महाराष्ट्र सरकार की प्रत्यक्ष लाभ हस्तांतरण योजना।",
        "benefit": "Subsidizes 50% to 60% of the cost for purchasing farm machinery, tractors, and installing micro-irrigation systems.",
        "benefit_kn": "ಕೃಷಿ ಯಂತ್ರೋಪಕರಣಗಳು, ಟ್ರಾಕ್ಟರ್‌ಗಳು ಮತ್ತು ಸೂಕ್ಷ್ಮ ನೀರಾವರಿ ವ್ಯವಸ್ಥೆಗಳ ಸ್ಥಾಪನೆಗೆ ಶೇಕಡಾ 50 ರಿಂದ 60 ರಷ್ಟು ಸಬ್ಸಿಡಿ.",
        "benefit_hi": "कृषि मशीनरी, ट्रैक्टर खरीदने और सूक्ष्म सिंचाई प्रणाली स्थापित करने के लिए 50% से 60% की सब्सिडी।",
        "eligibility": "Registered farmers in Maharashtra",
        "state": "Maharashtra",
        "category": "State Scheme",
        "url": "https://mahadbt.maharashtra.gov.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "Naandi Foundation Horticulture Support",
        "name_kn": "ನಾಂದಿ ಫೌಂಡೇಶನ್ ತೋಟಗಾರಿಕೆ ಬೆಂಬಲ",
        "name_hi": "नांदी फाउंडेशन बागवानी सहायता",
        "description": "An NGO initiative supporting grape and pomegranate growers with training in zero-chemical organic disease management.",
        "description_kn": "ದ್ರಾಕ್ಷಿ ಮತ್ತು ದಾಳಿಂಬೆ ಬೆಳೆಗಾರರಿಗೆ ರಾಸಾಯನಿಕ ರಹಿತ ಸಾವಯವ ರೋಗ ನಿರ್ವಹಣೆಯಲ್ಲಿ ತರಬೇತಿ ನೀಡುವ ಒಂದು NGO ಉಪಕ್ರಮ.",
        "description_hi": "अंगूर और अनार उत्पादकों को बिना रसायन के जैविक रोग प्रबंधन में प्रशिक्षण देने वाली एक एनजीओ पहल।",
        "benefit": "Free biological pest control kits, organic compost, and hands-on training on sustainable canopy management.",
        "benefit_kn": "ಉಚಿತ ಜೈವಿಕ ಕೀಟ ನಿಯಂತ್ರಣ ಕಿಟ್‌ಗಳು, ಸಾವಯವ ಗೊಬ್ಬರ ಮತ್ತು ಸುಸ್ಥಿರ ಮೇಲಾವರಣ ನಿರ್ವಹಣೆಯ ಪ್ರಾಯೋಗಿಕ ತರಬೇತಿ.",
        "benefit_hi": "निशुल्क जैविक कीट नियंत्रण किट, जैविक खाद, और टिकाऊ कैनोपी प्रबंधन पर व्यावहारिक प्रशिक्षण।",
        "eligibility": "Grape and pomegranate growers in Maharashtra",
        "state": "Maharashtra",
        "category": "Private Initiative",
        "url": "https://www.naandi.org",
        "active": True,
    },
    # ── PUNJAB ──
    {
        "_id": generate_id(),
        "name": "Pani Bachao Paise Kamao",
        "name_kn": "ಪಾನಿ ಬಚಾವೋ ಪೈಸೆ ಕಮಾವೋ",
        "name_hi": "पानी बचाओ पैसे कमाओ",
        "description": "Punjab government scheme promoting groundwater conservation by rewarding farmers financially for saving electricity and water.",
        "description_kn": "ರೈತರು ವಿದ್ಯುತ್ ಮತ್ತು ನೀರನ್ನು ಉಳಿಸುವುದಕ್ಕಾಗಿ ಆರ್ಥಿಕವಾಗಿ ಪ್ರೋತ್ಸಾಹಿಸುವ ಮೂಲಕ ಅಂತರ್ಜಲ ಸಂರಕ್ಷಣೆಯನ್ನು ಉತ್ತೇಜಿಸುವ ಪಂಜಾಬ್ ಸರ್ಕಾರದ ಯೋಜನೆ.",
        "description_hi": "किसानों को बिजली और पानी बचाने के लिए वित्तीय रूप से पुरस्कृत करके भूजल संरक्षण को बढ़ावा देने वाली पंजाब सरकार की योजना।",
        "benefit": "Direct cash transfer of ₹4 per unit of electricity saved below the fixed consumption limit for agriculture tube wells.",
        "benefit_kn": "ಕೃಷಿ ಕೊಳವೆಬಾವಿಗಳಿಗೆ ನಿಗದಿಪಡಿಸಿದ ಬಳಕೆ ಮಿತಿಗಿಂತ ಕಡಿಮೆ ವಿದ್ಯುತ್ ಉಳಿಸಿದರೆ ಪ್ರತಿ ಯೂನಿಟ್‌ಗೆ ₹4 ರಂತೆ ನೇರ ನಗದು ವರ್ಗಾವಣೆ.",
        "benefit_hi": "कृषि नलकूपों के लिए निर्धारित खपत सीमा से कम बिजली बचाने पर ₹4 प्रति यूनिट का सीधा नकद हस्तांतरण।",
        "eligibility": "Farmers in Punjab with metered agricultural tube wells",
        "state": "Punjab",
        "category": "State Scheme",
        "url": "https://www.pspcl.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "The Kalgidhar Society Organic Drive",
        "name_kn": "ದಿ ಕಲ್ಗಿಧರ್ ಸೊಸೈಟಿ ಸಾವಯವ ಅಭಿಯಾನ",
        "name_hi": "द कलगीधर सोसाइटी जैविक अभियान",
        "description": "NGO program assisting rural farmers in Punjab to transition from intensive chemical agriculture to sustainable organic farming.",
        "description_kn": "ಪಂಜಾಬ್‌ನ ಗ್ರಾಮೀಣ ರೈತರು ತೀವ್ರ ರಾಸಾಯನಿಕ ಕೃಷಿಯಿಂದ ಸುಸ್ಥಿರ ಸಾವಯವ ಕೃಷಿಗೆ ಬದಲಾಗಲು ಸಹಾಯ ಮಾಡುವ NGO ಕಾರ್ಯಕ್ರಮ.",
        "description_hi": "पंजाब के ग्रामीण किसानों को सघन रासायनिक कृषि से टिकाऊ जैविक खेती की ओर बढ़ने में सहायता करने वाला एनजीओ कार्यक्रम।",
        "benefit": "Provides bio-fertilizers, organic seeds, and free soil testing to support chemical-free wheat and paddy farming.",
        "benefit_kn": "ರಾಸಾಯನಿಕ ರಹಿತ ಗೋಧಿ ಮತ್ತು ಭತ್ತದ ಕೃಷಿಯನ್ನು ಬೆಂಬಲಿಸಲು ಜೈವಿಕ ರಸಗೊಬ್ಬರಗಳು, ಸಾವಯವ ಬೀಜಗಳು ಮತ್ತು ಉಚಿತ ಮಣ್ಣಿನ ಪರೀಕ್ಷೆಯನ್ನು ಒದಗಿಸುತ್ತದೆ.",
        "benefit_hi": "रसायन मुक्त गेहूं और धान की खेती का समर्थन करने के लिए जैव-उर्वरक, जैविक बीज और मुफ्त मिट्टी परीक्षण प्रदान करता है।",
        "eligibility": "Farmers in Punjab transitioning to organic farming",
        "state": "Punjab",
        "category": "Private Initiative",
        "url": "https://barusahib.org",
        "active": True,
    },
    # ── TAMIL NADU ──
    {
        "_id": generate_id(),
        "name": "Kuruvai Cultivation Support Scheme",
        "name_kn": "ಕುರುವೈ ಬೇಸಾಯ ಬೆಂಬಲ ಯೋಜನೆ",
        "name_hi": "कुरुवई खेती सहायता योजना",
        "description": "Tamil Nadu government scheme providing complete agricultural input subsidies to delta district farmers during the Kuruvai season.",
        "description_kn": "ಕುರುವೈ ಹಂಗಾಮಿನಲ್ಲಿ ಡೆಲ್ಟಾ ಜಿಲ್ಲೆಯ ರೈತರಿಗೆ ಸಂಪೂರ್ಣ ಕೃಷಿ ಪರಿಕರಗಳ ಸಬ್ಸಿಡಿಯನ್ನು ಒದಗಿಸುವ ತಮಿಳುನಾಡು ಸರ್ಕಾರದ ಯೋಜನೆ.",
        "description_hi": "कुरुवई सीजन के दौरान डेल्टा जिला किसानों को पूर्ण कृषि इनपुट सब्सिडी प्रदान करने वाली तमिलनाडु सरकार की योजना।",
        "benefit": "100% subsidy on certified paddy seeds and chemical/bio-fertilizers up to ₹1,850 per acre for Kuruvai season.",
        "benefit_kn": "ಕುರುವೈ ಹಂಗಾಮಿಗೆ ಪ್ರತಿ ಎಕರೆಗೆ ₹1,850 ರವರೆಗೆ ಪ್ರಮಾಣೀಕೃತ ಭತ್ತದ ಬೀಜಗಳು ಮತ್ತು ರಾಸಾಯನಿಕ/ಜೈವಿಕ ಗೊಬ್ಬರಗಳ ಮೇಲೆ 100% ಸಬ್ಸಿಡಿ.",
        "benefit_hi": "कुरुवई सीजन के लिए प्रति एकड़ ₹1,850 तक प्रमाणित धान के बीजों और रासायनिक/जैव-उर्वरकों पर 100% सब्सिडी।",
        "eligibility": "Delta region farmers in Tamil Nadu",
        "state": "Tamil Nadu",
        "category": "State Scheme",
        "url": "https://www.tn.gov.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "MSSRF Climate-Resilient Farming",
        "name_kn": "ಎಂಎಸ್ಎಸ್ಆರ್ಎಫ್ ಹವಾಮಾನ-ಸ್ಥಿತಿಸ್ಥಾಪಕ ಕೃಷಿ",
        "name_hi": "एमएसएसआरएफ जलवायु-अनुकूल खेती",
        "description": "NGO initiative training coastal Tamil Nadu farmers in adapting to climate change using salinity-resistant crops and smart water harvesting.",
        "description_kn": "ಲವಣಾಂಶ-ನಿರೋಧಕ ಬೆಳೆಗಳು ಮತ್ತು ಸ್ಮಾರ್ಟ್ ನೀರು ಕೊಯ್ಲು ಬಳಸಿ ಹವಾಮಾನ ಬದಲಾವಣೆಗೆ ಹೊಂದಿಕೊಳ್ಳಲು ತಮಿಳುನಾಡಿನ ಕರಾವಳಿ ರೈತರಿಗೆ ತರಬೇತಿ ನೀಡುವ NGO ಉಪಕ್ರಮ.",
        "description_hi": "लवणता-प्रतिरोधी फसलों और स्मार्ट जल संचयन का उपयोग करके जलवायु परिवर्तन के अनुकूल होने के लिए तटीय तमिलनाडु के किसानों को प्रशिक्षित करने की एनजीओ पहल।",
        "benefit": "Supplies saline-resistant crop seeds, solar irrigation pumps, and weather advisory alerts directly to mobile phones.",
        "benefit_kn": "ಲವಣಾಂಶ-ನಿರೋಧಕ ಬೆಳೆ ಬೀಜಗಳು, ಸೌರ ನೀರಾವರಿ ಪಂಪ್‌ಗಳು ಮತ್ತು ಹವಾಮಾನ ಸಲಹಾ ಎಚ್ಚರಿಕೆಗಳನ್ನು ನೇರವಾಗಿ ಮೊಬೈಲ್‌ಗೆ ಒದಗಿಸುತ್ತದೆ.",
        "benefit_hi": "लवणता-प्रतिरोधी फसल के बीज, सौर सिंचाई पंप और सीधे मोबाइल फोन पर मौसम सलाहकार अलर्ट प्रदान करता है।",
        "eligibility": "Coastal and dryland farmers in Tamil Nadu",
        "state": "Tamil Nadu",
        "category": "Private Initiative",
        "url": "https://www.mssrf.org",
        "active": True,
    },
    # ── ANDHRA PRADESH ──
    {
        "_id": generate_id(),
        "name": "YSR Rythu Bharosa",
        "name_kn": "ವೈಎಸ್ಆರ್ ರೈತು ಭರೋಸಾ",
        "name_hi": "वाईएसआर रायथू भरोसा",
        "description": "Andhra Pradesh state scheme providing direct financial assistance to landholding and tenant farmers to support cultivation costs.",
        "description_kn": "ಬೇಸಾಯದ ವೆಚ್ಚವನ್ನು ಬೆಂಬಲಿಸಲು ಭೂಹಿಡುವಳಿ ಮತ್ತು ಗೇಣಿ ರೈತರಿಗೆ ನೇರ ಆರ್ಥಿಕ ಸಹಾಯವನ್ನು ಒದಗಿಸುವ ಆಂಧ್ರಪ್ರದೇಶ ರಾಜ್ಯದ ಯೋಜನೆ.",
        "description_hi": "खेती की लागत का समर्थन करने के लिए भूमिधारक और काश्तकार किसानों को सीधे वित्तीय सहायता प्रदान करने वाली आंध्र प्रदेश राज्य की योजना।",
        "benefit": "Direct financial assistance of ₹13,500 per year, which includes ₹7,500 from the state and ₹6,000 from the central government.",
        "benefit_kn": "ವರ್ಷಕ್ಕೆ ₹13,500 ನೇರ ಆರ್ಥಿಕ ಸಹಾಯ, ಇದರಲ್ಲಿ ರಾಜ್ಯದಿಂದ ₹7,500 ಮತ್ತು ಕೇಂದ್ರ ಸರ್ಕಾರದಿಂದ ₹6,000 ಸೇರಿದೆ.",
        "benefit_hi": "प्रति वर्ष ₹13,500 की सीधी वित्तीय सहायता, जिसमें राज्य से ₹7,500 और केंद्र सरकार से ₹6,000 शामिल हैं।",
        "eligibility": "All landholding and registered tenant farmers in Andhra Pradesh",
        "state": "Andhra Pradesh",
        "category": "State Scheme",
        "url": "https://rythubharosa.ap.gov.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "Rythu Sadhikara Samstha Natural Farming",
        "name_kn": "ರೈತು ಸಧಿಕಾರ ಸಂಸ್ಥೆ ನೈಸರ್ಗಿಕ ಕೃಷಿ",
        "name_hi": "रायथू सधकारा संस्था प्राकृतिक खेती",
        "description": "A state-backed NGO program promoting Zero-Budget Natural Farming (ZBNF) to eliminate chemical inputs and reduce debt.",
        "description_kn": "ರಾಸಾಯನಿಕ ಮುಕ್ತ ಕೃಷಿಯನ್ನು ಉತ್ತೇಜಿಸಲು ಮತ್ತು ರೈತರ ಸಾಲದ ಹೊರೆಯನ್ನು ಕಡಿಮೆ ಮಾಡಲು ಶೂನ್ಯ ಬಂಡವಾಳ ನೈಸರ್ಗಿಕ ಕೃಷಿ (ZBNF) ಪ್ರಚಾರ ಮಾಡುವ ಯೋಜನೆ.",
        "description_hi": "रासायनिक इनपुट को समाप्त करने और ऋण को कम करने के लिए शून्य-बजट प्राकृतिक खेती (ZBNF) को बढ़ावा देने वाला राज्य-समर्थित एनजीओ कार्यक्रम।",
        "benefit": "Subsidized bio-inoculants (Jeevamrutha), organic seeds, and dedicated technical training by community resource persons.",
        "benefit_kn": "ಸಬ್ಸಿಡಿ ದರದ ಜೈವಿಕ ಗೊಬ್ಬರಗಳು (ಜೀವಾಮೃತ), ಸಾವಯವ ಬೀಜಗಳು ಮತ್ತು ಸಮುದಾಯ ಸಂಪನ್ಮೂಲ ವ್ಯಕ್ತಿಗಳಿಂದ ತಾಂತ್ರಿಕ ತರಬೇತಿ.",
        "benefit_hi": "रियायती जैव-उर्वरक (जीवामृत), जैविक बीज और सामुदायिक संसाधन व्यक्तियों द्वारा विशेष तकनीकी प्रशिक्षण।",
        "eligibility": "Farmers in Andhra Pradesh practicing or transitioning to natural farming",
        "state": "Andhra Pradesh",
        "category": "Private Initiative",
        "url": "http://apzbnf.in",
        "active": True,
    },
    # ── UTTAR PRADESH ──
    {
        "_id": generate_id(),
        "name": "UP Pankaj Organic Krishi Subsidy",
        "name_kn": "ಯುಪಿ ಸಾವಯವ ಕೃಷಿ ಸಬ್ಸಿಡಿ",
        "name_hi": "यूपी जैविक कृषि सब्सिडी",
        "description": "Uttar Pradesh government scheme supporting farmers to establish organic manure units to restore soil health and fertility.",
        "description_kn": "ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಮತ್ತು ಫಲವತ್ತತೆಯನ್ನು ಮರುಸ್ಥಾಪಿಸಲು ಸಾವಯವ ಗೊಬ್ಬರ ಘಟಕಗಳನ್ನು ಸ್ಥಾಪಿಸಲು ರೈತರಿಗೆ ಬೆಂಬಲ ನೀಡುವ ಉತ್ತರ ಪ್ರದೇಶ ಸರ್ಕಾರದ ಯೋಜನೆ.",
        "description_hi": "मिट्टी के स्वास्थ्य और उर्वरता को बहाल करने के लिए जैविक खाद इकाइयों की स्थापना में किसानों की सहायता करने वाली उत्तर प्रदेश सरकार की योजना।",
        "benefit": "Provides a 75% financial subsidy up to ₹15,000 for constructing vermicompost pits and purchasing organic inputs.",
        "benefit_kn": "ವರ್ಮಿಕಾಂಪೋಸ್ಟ್ (ಎರೆಗೊಬ್ಬರ) ತೊಟ್ಟಿಗಳ ನಿರ್ಮಾಣ ಮತ್ತು ಸಾವಯವ ಪರಿಕರಗಳ ಖರೀದಿಗೆ ₹15,000 ವರೆಗೆ ಶೇಕಡಾ 75 ರಷ್ಟು ಆರ್ಥಿಕ ಸಬ್ಸಿಡಿ.",
        "benefit_hi": "वर्मीकम्पोस्ट गड्ढों के निर्माण और जैविक इनपुट खरीदने के लिए ₹15,000 तक 75% वित्तीय सब्सिडी प्रदान करता है।",
        "eligibility": "Registered farmers in Uttar Pradesh",
        "state": "UP",
        "category": "State Scheme",
        "url": "http://upagriculture.com",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "Gorakhpur Environmental Action Group",
        "name_kn": "ಗೋರಖ್‌ಪುರ ಪರಿಸರ ಕ್ರಿಯಾ ಗುಂಪು",
        "name_hi": "गोरखपुर पर्यावरण एक्शन ग्रुप",
        "description": "An NGO promoting sustainable, climate-resilient agriculture and ecological farming techniques among smallholder farmers in Eastern UP.",
        "description_kn": "ಪರ್ವ ಯುಪಿಯ ಸಣ್ಣ ರೈತರಲ್ಲಿ ಸುಸ್ಥಿರ, ಹವಾಮಾನ-ಸ್ಥಿತಿಸ್ಥಾಪಕ ಕೃಷಿ ಮತ್ತು ಪರಿಸರ ಕೃಷಿ ತಂತ್ರಗಳನ್ನು ಉತ್ತೇಜಿಸುವ ಸ್ವಯಂಸೇವಾ ಸಂಸ್ಥೆ.",
        "description_hi": "पूर्वी यूपी में छोटे किसानों के बीच टिकाऊ, जलवायु-अनुकूल कृषि और पारिस्थितिक खेती तकनीकों को बढ़ावा देने वाला एक एनजीओ।",
        "benefit": "Provides bio-pesticides, flood-resilient seeds, and training on multi-cropping systems to smallholder farming families.",
        "benefit_kn": "ಸಣ್ಣ ಹಿಡುವಳಿ ರೈತ ಕುಟುಂಬಗಳಿಗೆ ಜೈವಿಕ ಕೀಟನಾಶಕಗಳು, ಪ್ರವಾಹ-ನಿರೋಧಕ ಬೀಜಗಳು ಮತ್ತು ಬಹು-ಬೆಳೆ ಪದ್ಧತಿಯ ಬಗ್ಗೆ ತರಬೇತಿ ನೀಡುತ್ತದೆ.",
        "benefit_hi": "छोटे किसान परिवारों को जैव-कीटनाशक, बाढ़-अनुकूल बीज और बहु-फसली प्रणालियों पर प्रशिक्षण प्रदान करता है।",
        "eligibility": "Small and marginal farmers in Eastern Uttar Pradesh",
        "state": "UP",
        "category": "Private Initiative",
        "url": "http://geagindia.org",
        "active": True,
    },
    # ── RAJASTHAN ──
    {
        "_id": generate_id(),
        "name": "Rajasthan Mukhyamantri Rajshri Yojana",
        "name_kn": "ರಾಜಸ್ಥಾನ ಮುಖ್ಯಮಂತ್ರಿ ರಾಜಶ್ರೀ ಯೋಜನೆ",
        "name_hi": "राजस्थान मुख्यमंत्री राजश्री योजना",
        "description": "Rajasthan state scheme providing financial aid to women and girl children of farming families to promote education and welfare.",
        "description_kn": "ಶಿಕ್ಷಣ ಮತ್ತು ಕಲ್ಯಾಣವನ್ನು ಉತ್ತೇಜಿಸಲು ರೈತ ಕುಟುಂಬಗಳ ಮಹಿಳೆಯರು ಮತ್ತು ಹೆಣ್ಣು ಮಕ್ಕಳಿಗೆ ಆರ್ಥಿಕ ಸಹಾಯವನ್ನು ಒದಗಿಸುವ ರಾಜಸ್ಥಾನ ರಾಜ್ಯದ ಯೋಜನೆ.",
        "description_hi": "शिक्षा और कल्याण को बढ़ावा देने के लिए किसान परिवारों की महिलाओं और बालिकाओं को वित्तीय सहायता प्रदान करने वाली राजस्थान राज्य की योजना।",
        "benefit": "Financial assistance of up to ₹50,000 in installments for the health, education, and development of girls in farming families.",
        "benefit_kn": "ರೈತ ಕುಟುಂಬಗಳಲ್ಲಿನ ಹೆಣ್ಣು ಮಕ್ಕಳ ಆರೋಗ್ಯ, ಶಿಕ್ಷಣ ಮತ್ತು ಅಭಿವೃದ್ಧಿಗಾಗಿ ಹಂತ ಹಂತವಾಗಿ ₹50,000 ವರೆಗೆ ಆರ್ಥಿಕ ಸಹಾಯ.",
        "benefit_hi": "किसान परिवारों में बेटियों के स्वास्थ्य, शिक्षा और विकास के लिए किश्तों में ₹50,000 तक की वित्तीय सहायता।",
        "eligibility": "Farming families with girl children in Rajasthan",
        "state": "Rajasthan",
        "category": "State Scheme",
        "url": "https://rajasthan.gov.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "Lupin Foundation Desert Agriculture",
        "name_kn": "ಲುಪಿನ್ ಫೌಂಡೇಶನ್ ಮರುಭೂಮಿ ಕೃಷಿ",
        "name_hi": "ल्यूपिन फाउंडेशन मरुस्थल कृषि",
        "description": "NGO initiative supporting arid land farmers in Rajasthan with water conservation structures and drought-tolerant horticulture.",
        "description_kn": "ರಾಜಸ್ಥಾನದ ಶುಷ್ಕ ಭೂಮಿ ರೈತರಿಗೆ ನೀರು ಸಂರಕ್ಷಣೆ ಮತ್ತು ಬರ-ನಿರೋಧಕ ತೋಟಗಾರಿಕಾ ತಂತ್ರಜ್ಞಾನಗಳ ಮೂಲಕ ಬೆಂಬಲ ನೀಡುವ NGO ಉಪಕ್ರಮ.",
        "description_hi": "राजस्थान के शुष्क भूमि किसानों को जल संरक्षण संरचनाओं और सूखा-सहिष्णु बागवानी के माध्यम से सहायता करने वाली एनजीओ पहल।",
        "benefit": "Subsidized rainwater harvesting tanks (Taankas), drip systems, and drought-resistant fruit saplings like Ber and Gunda.",
        "benefit_kn": "ಸಬ್ಸಿಡಿ ದರದ ಮಳೆನೀರು ಕೊಯ್ಲು ತೊಟ್ಟಿಗಳು (ಟಾಕಾಗಳು), ಹನಿ ನೀರಾವರಿ ಮತ್ತು ಬರ-ನಿರೋಧಕ ಹಣ್ಣಿನ ಸಸಿಗಳ (ಬೋರ್, ಗುಂಡಾ) ವಿತರಣೆ.",
        "benefit_hi": "रियायती वर्षा जल संचयन टैंक (टांका), ड्रिप प्रणाली, और बेर और गुंडा जैसे सूखा-प्रतिरोधी फलों के पौधे।",
        "eligibility": "Arid region farmers in Rajasthan",
        "state": "Rajasthan",
        "category": "Private Initiative",
        "url": "http://www.lupinfoundation.in",
        "active": True,
    },
    # ── GUJARAT ──
    {
        "_id": generate_id(),
        "name": "Gujarat Saat Pagla Kalyanna",
        "name_kn": "ಗುಜರಾತ್ ಸಾತ್ ಪಗ್ಲಾ ಕಲ್ಯಾಣ್",
        "name_hi": "गुजरात सात पगला कल्याण",
        "description": "Gujarat government scheme offering seven steps of welfare, including storage facility subsidies and mobile crop selling carts.",
        "description_kn": "ದಾಸ್ತಾನು ಸೌಲಭ್ಯ ಸಬ್ಸಿಡಿಗಳು ಮತ್ತು ಬೆಳೆ ಮಾರಾಟದ ಮೊಬೈಲ್ ಕಾರ್ಟ್‌ಗಳು ಸೇರಿದಂತೆ ಏಳು ಹಂತಗಳ ಕಲ್ಯಾಣ ಸೌಲಭ್ಯಗಳನ್ನು ನೀಡುವ ಗುಜರಾತ್ ಸರ್ಕಾರದ ಯೋಜನೆ.",
        "description_hi": "भंडारण सुविधा सब्सिडी और मोबाइल फसल बिक्री कार्ट सहित कल्याण के सात कदम प्रदान करने वाली गुजरात सरकार की योजना।",
        "benefit": "Provides a 100% financial subsidy up to ₹50,000 for farm storage structures and crop transport subsidies.",
        "benefit_kn": "ಕೃಷಿ ದಾಸ್ತಾನು ಜಾಗಗಳ ನಿರ್ಮಾಣಕ್ಕಾಗಿ ಮತ್ತು ಬೆಳೆ ಸಾಗಾಣಿಕಾ ವೆಚ್ಚದ ಮೇಲೆ ₹50,000 ವರೆಗೆ ಸಂಪೂರ್ಣ 100% ಸಬ್ಸಿಡಿ.",
        "benefit_hi": "कृषि भंडारण संरचनाओं और फसल परिवहन सब्सिडी के लिए ₹50,000 तक 100% वित्तीय सब्सिडी प्रदान करता है।",
        "eligibility": "Registered farmers in Gujarat",
        "state": "Gujarat",
        "category": "State Scheme",
        "url": "https://ikhedut.gujarat.gov.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "SEWA Organic Mahila Agriculture",
        "name_kn": "ಸೇವಾ ಸಾವಯವ ಮಹಿಳಾ ಕೃಷಿ",
        "name_hi": "सेवा जैविक महिला कृषि",
        "description": "An NGO cooperative training and supporting smallholder women farmers in Gujarat in organic agriculture and collective marketing.",
        "description_kn": "ಗುಜರಾತ್‌ನ ಸಣ್ಣ ಹಿಡುವಳಿ ಮಹಿಳಾ ರೈತರಿಗೆ ಸಾವಯವ ಕೃಷಿ ಮತ್ತು ಸಾಮೂಹಿಕ ಮಾರಾಟದಲ್ಲಿ ತರಬೇತಿ ಹಾಗೂ ಬೆಂಬಲ ನೀಡುವ NGO ಸಹಕಾರ ಸಂಘ.",
        "description_hi": "गुजरात में छोटी महिला किसानों को जैविक कृषि और सामूहिक विपणन में प्रशिक्षित और सहायता करने वाली एक एनजीओ सहकारी संस्था।",
        "benefit": "Establishes community seed banks, provides organic pesticide kits, and offers direct market linkage for organic produce.",
        "benefit_kn": "ಸಮುದಾಯ ಬೀಜ ಬ್ಯಾಂಕ್‌ಗಳ ಸ್ಥಾಪನೆ, ಸಾವಯವ ಕೀಟನಾಶಕ ಕಿಟ್‌ಗಳ ವಿತರಣೆ ಮತ್ತು ಸಾವಯವ ಉತ್ಪನ್ನಗಳಿಗೆ ನೇರ ಮಾರುಕಟ್ಟೆ ಸಂಪರ್ಕ ಒದಗಿಸುತ್ತದೆ.",
        "benefit_hi": "सामुदायिक बीज बैंकों की स्थापना, जैविक कीटनाशक किट, और जैविक उत्पादों के लिए सीधे बाजार संपर्क प्रदान करता है।",
        "eligibility": "Women farmers and self-help groups in Gujarat",
        "state": "Gujarat",
        "category": "Private Initiative",
        "url": "https://www.sewa.org",
        "active": True,
    },
    # ── WEST BENGAL ──
    {
        "_id": generate_id(),
        "name": "Krishak Bandhu Scheme",
        "name_kn": "ಕೃಷಕ ಬಂಧು ಯೋಜನೆ",
        "name_hi": "कृषक बंधु योजना",
        "description": "West Bengal government scheme providing financial support and life insurance coverage to farming families.",
        "description_kn": "ರೈತ ಕುಟುಂಬಗಳಿಗೆ ಆರ್ಥಿಕ ಬೆಂಬಲ ಮತ್ತು ಆಕಸ್ಮಿಕ ಜೀವ ವಿಮಾ ರಕ್ಷಣೆಯನ್ನು ಒದಗಿಸುವ ಪಶ್ಚಿಮ ಬಂಗಾಳ ಸರ್ಕಾರದ ಯೋಜನೆ.",
        "description_hi": "किसान परिवारों को वित्तीय सहायता और जीवन बीमा कवरेज प्रदान करने वाली पश्चिम बंगाल सरकार की योजना।",
        "benefit": "Financial assistance of up to ₹10,000 per year for landowners, and a life insurance death benefit of ₹2,00,000.",
        "benefit_kn": "ಭೂಮಾಲೀಕರಿಗೆ ವರ್ಷಕ್ಕೆ ₹10,000 ವರೆಗೆ ಆರ್ಥಿಕ ಸಹಾಯ, ಮತ್ತು ರೈತ ಮರಣ ಹೊಂದಿದಲ್ಲಿ ₹2,00,000 ಜೀವ ವಿಮಾ ಪರಿಹಾರ.",
        "benefit_hi": "भूस्वामियों के लिए प्रति वर्ष ₹10,000 तक की वित्तीय सहायता, और ₹2,00,000 का जीवन बीमा मृत्यु लाभ।",
        "eligibility": "All landholding farmers and sharecroppers in West Bengal",
        "state": "West Bengal",
        "category": "State Scheme",
        "url": "https://krishakbandhu.wb.gov.in",
        "active": True,
    },
    {
        "_id": generate_id(),
        "name": "DRCSC Sustainable Agriculture Project",
        "name_kn": "ಡಿಆರ್‌ಸಿಎಸ್‌ಸಿ ಸುಸ್ಥಿರ ಕೃಷಿ ಯೋಜನೆ",
        "name_hi": "डीआरसीएससी सतत कृषि परियोजना",
        "description": "NGO project promoting bio-diverse integrated farming, organic pest management, and climate adaptation in West Bengal.",
        "description_kn": "ಪಶ್ಚಿಮ ಬಂಗಾಳದಲ್ಲಿ ಜೀವವೈವಿಧ್ಯ ಸಮಗ್ರ ಕೃಷಿ, ಸಾವಯವ ಕೀಟ ನಿರ್ವಹಣೆ ಮತ್ತು ಹವಾಮಾನ ಹೊಂದಾಣಿಕೆಯನ್ನು ಉತ್ತೇಜಿಸುವ NGO ಯೋಜನೆ.",
        "description_hi": "पश्चिम बंगाल में जैव-विविध एकीकृत खेती, जैविक कीट प्रबंधन और जलवायु अनुकूलन को बढ़ावा देने वाली एनजीओ परियोजना।",
        "benefit": "Bio-diversity farming kits, rainwater harvesting pond liners, and training on integrated organic farming.",
        "benefit_kn": "ಜೈವಿಕ ವೈವಿಧ್ಯಮಯ ಕೃಷಿ ಕಿಟ್‌ಗಳು, ಮಳೆನೀರು ಸಂಗ್ರಹಣೆ ಹೊಂಡದ ಲೈನರ್‌ಗಳು ಮತ್ತು ಸಮಗ್ರ ಸಾವಯವ ಕೃಷಿಯ ತರಬೇತಿ.",
        "benefit_hi": "जैव-विविधता कृषि किट, वर्षा जल संचयन तालाब लाइनर, और एकीकृत जैविक खेती पर प्रशिक्षण।",
        "eligibility": "Smallholder farmers in West Bengal",
        "state": "West Bengal",
        "category": "Private Initiative",
        "url": "http://www.drcsc.org",
        "active": True,
    }
]


def seed_schemes():
    col = government_schemes_col()
    col.drop()
    col.insert_many(SEED_SCHEMES)
    log.info(f"Seeded {len(SEED_SCHEMES)} government schemes successfully.")



def get_all_schemes(state: str = None, category: str = None) -> list:
    """Fetch schemes with optional filtering by state and category."""
    query = {"active": True}
    if state:
        query["$or"] = [
            {"state": {"$regex": state, "$options": "i"}},
            {"state": "All India"},
        ]
    if category:
        query["category"] = {"$regex": category, "$options": "i"}

    cursor = government_schemes_col().find(query).sort("name", 1)
    return list(cursor)


def get_scheme_by_id(scheme_id: str) -> dict:
    return government_schemes_col().find_one({"_id": scheme_id})


def log_application(user_id: str, scheme_id: str):
    """Log that a user started an application for a scheme."""
    from database import support_tickets_col
    ticket = {
        "_id": generate_id(),
        "user_id": user_id,
        "scheme_id": scheme_id,
        "type": "scheme_application",
        "status": "initiated",
        "created_at": datetime.utcnow(),
    }
    support_tickets_col().insert_one(ticket)
    log.info(f"Scheme application logged: user={user_id}, scheme={scheme_id}")
    return ticket["_id"]
